### ISSUE TITLE
How to use? i ended up with errors

### ISSUE THREAD

**Issue by keshavbhatt** [mpalazzolo/soundcloud-charts-api#1]
I tried example code and its giving me errors:

`/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "/tmp/new.py", line 3, in <module>
    sc = SoundCloudCharts()
  File "/usr/local/lib/python2.7/dist-packages/soundcloudcharts/client.py", line 13, in __init__
    super().__init__(root='https://api-v2.soundcloud.com/', proxies=proxies)
TypeError: super() takes at least 1 argument (0 given)
`

**Comment by mpalazzolo** [comment]
It seems like the issue is because you are using Python 2.7. Check out this link:
[https://stackoverflow.com/questions/38963018/typeerror-super-takes-at-least-1-argument-0-given-error-is-specific-to-any](url)

I developed and tested in Python 3. Try switching to 3 if possible and see if your problem persists.

**Comment by keshavbhatt** [comment]
gives 401 error now. 
I implemented my own php script to do it in my application [Olivia](https://github.com/keshavbhatt/olivia)
Thanks :)
